// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_IZrFLEeutPsCZUAnYqCgXaxup2oqi9w',
    appId: '1:225188156551:web:6253af4cd2202561111422',
    messagingSenderId: '225188156551',
    projectId: 'lexifocus-b41ff',
    authDomain: 'lexifocus-b41ff.firebaseapp.com',
    storageBucket: 'lexifocus-b41ff.firebasestorage.app',
    measurementId: 'G-XG0FEE32MR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfHhtPMrqoYN4Z7jmwh4p_iME4o0let4U',
    appId: '1:225188156551:android:9ec334005f206e6a111422',
    messagingSenderId: '225188156551',
    projectId: 'lexifocus-b41ff',
    storageBucket: 'lexifocus-b41ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp0rQVV9q2eMz2YrzMiXqJQJzgf5o-jjE',
    appId: '1:225188156551:ios:0123254f4b900b8d111422',
    messagingSenderId: '225188156551',
    projectId: 'lexifocus-b41ff',
    storageBucket: 'lexifocus-b41ff.firebasestorage.app',
    iosBundleId: 'com.example.miApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp0rQVV9q2eMz2YrzMiXqJQJzgf5o-jjE',
    appId: '1:225188156551:ios:0123254f4b900b8d111422',
    messagingSenderId: '225188156551',
    projectId: 'lexifocus-b41ff',
    storageBucket: 'lexifocus-b41ff.firebasestorage.app',
    iosBundleId: 'com.example.miApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_IZrFLEeutPsCZUAnYqCgXaxup2oqi9w',
    appId: '1:225188156551:web:bb579dfdbedaa651111422',
    messagingSenderId: '225188156551',
    projectId: 'lexifocus-b41ff',
    authDomain: 'lexifocus-b41ff.firebaseapp.com',
    storageBucket: 'lexifocus-b41ff.firebasestorage.app',
    measurementId: 'G-CVQCZ1ED9X',
  );
}
